<?php
	/*Class Generated by Brendon Irwin's Class Generator*/

	class Spotlight{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $cmsid;
		private $type;
		private $name;
		private $title;
		private $published;
		private $imagePath;
		private $link;
		private $newWindow;
		private $lastModified;
		private $tags;
		private $deleted;
		private $sunrise;
		private $sunset;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getCmsid(){
			return $this->cmsid;
		}

		function setCmsid($cmsid){
			$this->cmsid = $cmsid;
		}

		function getType(){
			return $this->type;
		}

		function setType($type){
			$this->type = $type;
		}

		function getName(){
			return $this->name;
		}

		function setName($name){
			$this->name = $name;
		}

		function getTitle(){
			return $this->title;
		}

		function setTitle($title){
			$this->title = $title;
		}

		function getPublished(){
			return $this->published;
		}

		function setPublished($published){
			$this->published = $published;
		}

		function getImagePath(){
			return $this->imagePath;
		}

		function setImagePath($imagePath){
			$this->imagePath = $imagePath;
		}

		function getLink(){
			return $this->link;
		}

		function setLink($link){
			$this->link = $link;
		}

		function getNewWindow(){
			return $this->newWindow;
		}

		function setNewWindow($newWindow){
			$this->newWindow = $newWindow;
		}

		function getLastModified(){
			return $this->lastModified;
		}

		function setLastModified($lastModified){
			$this->lastModified = $lastModified;
		}

		function getTags(){
			return $this->tags;
		}

		function setTags($tags){
			$this->tags = $tags;
		}

		function getDeleted(){
			return $this->deleted;
		}

		function setDeleted($deleted){
			$this->deleted = $deleted;
		}

		function getSunrise(){
			return $this->sunrise;
		}

		function setSunrise($sunrise){
			$this->sunrise = $sunrise;
		}

		function getSunset(){
			return $this->sunset;
		}

		function setSunset($sunset){
			$this->sunset = $sunset;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$spotlight = $query->fetchObject("spotlight");
					}
					if( is_object( $spotlight ) ){
						$spotlight->setConnection( $this->connection );
					}
					return $spotlight;
				}
			}
		}

		function getFromPost(){
			$this->setCmsid( (isset($_POST["cmsid"])) ? $_POST["cmsid"] : $this->getCmsid() );
			$this->setType( (isset($_POST["type"])) ? $_POST["type"] : $this->getType() );
			$this->setName( (isset($_POST["name"])) ? $_POST["name"] : $this->getName() );
			$this->setTitle( (isset($_POST["title"])) ? $_POST["title"] : $this->getTitle() );
			$this->setPublished( (isset($_POST["published"])) ? $_POST["published"] : $this->getPublished() );
			$this->setImagePath( (isset($_POST["imagePath"])) ? $_POST["imagePath"] : $this->getImagePath() );
			$this->setLink( (isset($_POST["link"])) ? $_POST["link"] : $this->getLink() );
			$this->setNewWindow( (isset($_POST["newWindow"])) ? $_POST["newWindow"] : $this->getNewWindow() );
			$this->setLastModified( (isset($_POST["lastModified"])) ? $_POST["lastModified"] : $this->getLastModified() );
			$this->setTags( (isset($_POST["tags"])) ? $_POST["tags"] : $this->getTags() );
			$this->setDeleted( (isset($_POST["deleted"])) ? $_POST["deleted"] : $this->getDeleted() );
			$this->setSunrise( (isset($_POST["sunrise"])) ? $_POST["sunrise"] : $this->getSunrise() );
			$this->setSunset( (isset($_POST["sunset"])) ? $_POST["sunset"] : $this->getSunset() );
		}

		function getFromRequest(){
			$this->setCmsid( (isset($_REQUEST["cmsid"])) ? $_REQUEST["cmsid"] : $this->getCmsid() );
			$this->setType( (isset($_REQUEST["type"])) ? $_REQUEST["type"] : $this->getType() );
			$this->setName( (isset($_REQUEST["name"])) ? $_REQUEST["name"] : $this->getName() );
			$this->setTitle( (isset($_REQUEST["title"])) ? $_REQUEST["title"] : $this->getTitle() );
			$this->setPublished( (isset($_REQUEST["published"])) ? $_REQUEST["published"] : $this->getPublished() );
			$this->setImagePath( (isset($_REQUEST["imagePath"])) ? $_REQUEST["imagePath"] : $this->getImagePath() );
			$this->setLink( (isset($_REQUEST["link"])) ? $_REQUEST["link"] : $this->getLink() );
			$this->setNewWindow( (isset($_REQUEST["newWindow"])) ? $_REQUEST["newWindow"] : $this->getNewWindow() );
			$this->setLastModified( (isset($_REQUEST["lastModified"])) ? $_REQUEST["lastModified"] : $this->getLastModified() );
			$this->setTags( (isset($_REQUEST["tags"])) ? $_REQUEST["tags"] : $this->getTags() );
			$this->setDeleted( (isset($_REQUEST["deleted"])) ? $_REQUEST["deleted"] : $this->getDeleted() );
			$this->setSunrise( (isset($_REQUEST["sunrise"])) ? $_REQUEST["sunrise"] : $this->getSunrise() );
			$this->setSunset( (isset($_REQUEST["sunset"])) ? $_REQUEST["sunset"] : $this->getSunset() );
		}

		function save(){
			$id = $this->getId();
			$cmsid = $this->getCmsid();
			$type = $this->getType();
			$name = $this->getName();
			$title = $this->getTitle();
			$published = $this->getPublished();
			$imagePath = $this->getImagePath();
			$link = $this->getLink();
			$newWindow = $this->getNewWindow();
			$lastModified = $this->getLastModified();
			$tags = $this->getTags();
			$deleted = $this->getDeleted();
			$sunrise = $this->getSunrise();
			$sunset = $this->getSunset();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `spotlight` SET `cmsid` = :cmsid ,`type` = :type ,`name` = :name ,`title` = :title ,`published` = :published ,`imagePath` = :imagePath ,`link` = :link ,`newWindow` = :newWindow ,`lastModified` = :lastModified ,`tags` = :tags ,`deleted` = :deleted ,`sunrise` = :sunrise ,`sunset` = :sunset WHERE `id` = :id");
					$query->bindParam('cmsid', $cmsid);
					$query->bindParam('type', $type);
					$query->bindParam('name', $name);
					$query->bindParam('title', $title);
					$query->bindParam('published', $published);
					$query->bindParam('imagePath', $imagePath);
					$query->bindParam('link', $link);
					$query->bindParam('newWindow', $newWindow);
					$query->bindParam('lastModified', $lastModified);
					$query->bindParam('tags', $tags);
					$query->bindParam('deleted', $deleted);
					$query->bindParam('sunrise', $sunrise);
					$query->bindParam('sunset', $sunset);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `spotlight` (`id`,`cmsid`,`type`,`name`,`title`,`published`,`imagePath`,`link`,`newWindow`,`lastModified`,`tags`,`deleted`,`sunrise`,`sunset`) VALUES (NULL,:cmsid,:type,:name,:title,:published,:imagePath,:link,:newWindow,:lastModified,:tags,:deleted,:sunrise,:sunset);");
					$query->bindParam(':cmsid', $cmsid);
					$query->bindParam(':type', $type);
					$query->bindParam(':name', $name);
					$query->bindParam(':title', $title);
					$query->bindParam(':published', $published);
					$query->bindParam(':imagePath', $imagePath);
					$query->bindParam(':link', $link);
					$query->bindParam(':newWindow', $newWindow);
					$query->bindParam(':lastModified', $lastModified);
					$query->bindParam(':tags', $tags);
					$query->bindParam(':deleted', $deleted);
					$query->bindParam(':sunrise', $sunrise);
					$query->bindParam(':sunset', $sunset);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `spotlight` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByCmsid($cmsid){
			if( $this->connection ){
				if( $cmsid == null && $this->getCmsid() != ""){
					$cmsid = $this->getCmsid();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `cmsid` = :cmsid LIMIT 1");
				$query->bindParam(':cmsid', $cmsid);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByType($type){
			if( $this->connection ){
				if( $type == null && $this->getType() != ""){
					$type = $this->getType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `type` = :type LIMIT 1");
				$query->bindParam(':type', $type);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByName($name){
			if( $this->connection ){
				if( $name == null && $this->getName() != ""){
					$name = $this->getName();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `name` = :name LIMIT 1");
				$query->bindParam(':name', $name);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByTitle($title){
			if( $this->connection ){
				if( $title == null && $this->getTitle() != ""){
					$title = $this->getTitle();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `title` = :title LIMIT 1");
				$query->bindParam(':title', $title);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByPublished($published){
			if( $this->connection ){
				if( $published == null && $this->getPublished() != ""){
					$published = $this->getPublished();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `published` = :published LIMIT 1");
				$query->bindParam(':published', $published);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByImagePath($imagePath){
			if( $this->connection ){
				if( $imagePath == null && $this->getImagePath() != ""){
					$imagePath = $this->getImagePath();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `imagePath` = :imagePath LIMIT 1");
				$query->bindParam(':imagePath', $imagePath);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByLink($link){
			if( $this->connection ){
				if( $link == null && $this->getLink() != ""){
					$link = $this->getLink();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `link` = :link LIMIT 1");
				$query->bindParam(':link', $link);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByNewWindow($newWindow){
			if( $this->connection ){
				if( $newWindow == null && $this->getNewWindow() != ""){
					$newWindow = $this->getNewWindow();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `newWindow` = :newWindow LIMIT 1");
				$query->bindParam(':newWindow', $newWindow);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByLastModified($lastModified){
			if( $this->connection ){
				if( $lastModified == null && $this->getLastModified() != ""){
					$lastModified = $this->getLastModified();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `lastModified` = :lastModified LIMIT 1");
				$query->bindParam(':lastModified', $lastModified);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByTags($tags){
			if( $this->connection ){
				if( $tags == null && $this->getTags() != ""){
					$tags = $this->getTags();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `tags` = :tags LIMIT 1");
				$query->bindParam(':tags', $tags);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByDeleted($deleted){
			if( $this->connection ){
				if( $deleted == null && $this->getDeleted() != ""){
					$deleted = $this->getDeleted();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `deleted` = :deleted LIMIT 1");
				$query->bindParam(':deleted', $deleted);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getBySunrise($sunrise){
			if( $this->connection ){
				if( $sunrise == null && $this->getSunrise() != ""){
					$sunrise = $this->getSunrise();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `sunrise` = :sunrise LIMIT 1");
				$query->bindParam(':sunrise', $sunrise);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getBySunset($sunset){
			if( $this->connection ){
				if( $sunset == null && $this->getSunset() != ""){
					$sunset = $this->getSunset();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `sunset` = :sunset LIMIT 1");
				$query->bindParam(':sunset', $sunset);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByCmsid($cmsid=null){
			if( $this->connection ){
				if( $cmsid == null && $this->getCmsid() != ""){
					$cmsid = $this->getCmsid();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `cmsid` = :cmsid");
				$query->bindParam(':cmsid', $cmsid);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( isset($potlights) && is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByType($type=null){
			if( $this->connection ){
				if( $type == null && $this->getType() != ""){
					$type = $this->getType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `type` = :type");
				$query->bindParam(':type', $type);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByName($name=null){
			if( $this->connection ){
				if( $name == null && $this->getName() != ""){
					$name = $this->getName();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `name` = :name");
				$query->bindParam(':name', $name);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByTitle($title=null){
			if( $this->connection ){
				if( $title == null && $this->getTitle() != ""){
					$title = $this->getTitle();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `title` = :title");
				$query->bindParam(':title', $title);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByPublished($published=null){
			if( $this->connection ){
				if( $published == null && $this->getPublished() != ""){
					$published = $this->getPublished();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `published` = :published");
				$query->bindParam(':published', $published);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByImagePath($imagePath=null){
			if( $this->connection ){
				if( $imagePath == null && $this->getImagePath() != ""){
					$imagePath = $this->getImagePath();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `imagePath` = :imagePath");
				$query->bindParam(':imagePath', $imagePath);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByLink($link=null){
			if( $this->connection ){
				if( $link == null && $this->getLink() != ""){
					$link = $this->getLink();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `link` = :link");
				$query->bindParam(':link', $link);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByNewWindow($newWindow=null){
			if( $this->connection ){
				if( $newWindow == null && $this->getNewWindow() != ""){
					$newWindow = $this->getNewWindow();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `newWindow` = :newWindow");
				$query->bindParam(':newWindow', $newWindow);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByLastModified($lastModified=null){
			if( $this->connection ){
				if( $lastModified == null && $this->getLastModified() != ""){
					$lastModified = $this->getLastModified();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `lastModified` = :lastModified");
				$query->bindParam(':lastModified', $lastModified);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByTags($tags=null){
			if( $this->connection ){
				if( $tags == null && $this->getTags() != ""){
					$tags = $this->getTags();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `tags` = :tags");
				$query->bindParam(':tags', $tags);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListByDeleted($deleted=null){
			if( $this->connection ){
				if( $deleted == null && $this->getDeleted() != ""){
					$deleted = $this->getDeleted();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `deleted` = :deleted");
				$query->bindParam(':deleted', $deleted);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListBySunrise($sunrise=null){
			if( $this->connection ){
				if( $sunrise == null && $this->getSunrise() != ""){
					$sunrise = $this->getSunrise();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `sunrise` = :sunrise");
				$query->bindParam(':sunrise', $sunrise);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		function getListBySunset($sunset=null){
			if( $this->connection ){
				if( $sunset == null && $this->getSunset() != ""){
					$sunset = $this->getSunset();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlight` WHERE `sunset` = :sunset");
				$query->bindParam(':sunset', $sunset);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlight") ){
						$spotlights[] = $result;
					}
					if( is_array( $spotlights ) ){
						return $spotlights;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="spotlight.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `spotlight` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < sizeof($numParams); $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("spotlight") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>