<?php
	/*Class Generated by Brendon Irwin's Class Generator*/

	class Spotlightlist{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $listName;
		private $description;
		private $owner;
		private $lastUpdated;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getListName(){
			return $this->listName;
		}

		function setListName($listName){
			$this->listName = $listName;
		}

		function getDescription(){
			return $this->description;
		}

		function setDescription($description){
			$this->description = $description;
		}

		function getOwner(){
			return $this->owner;
		}

		function setOwner($owner){
			$this->owner = $owner;
		}

		function getLastUpdated(){
			return $this->lastUpdated;
		}

		function setLastUpdated($lastUpdated){
			$this->lastUpdated = $lastUpdated;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$spotlightlist = $query->fetchObject("spotlightlist");
					}
					if( is_object( $spotlightlist ) ){
						$spotlightlist->setConnection( $this->connection );
					}
					return $spotlightlist;
				}
			}
		}

		function getFromPost(){
			$this->setListName( (isset($_POST["listName"])) ? $_POST["listName"] : $this->getListName() );
			$this->setDescription( (isset($_POST["description"])) ? $_POST["description"] : $this->getDescription() );
			$this->setOwner( (isset($_POST["owner"])) ? $_POST["owner"] : $this->getOwner() );
			$this->setLastUpdated( (isset($_POST["lastUpdated"])) ? $_POST["lastUpdated"] : $this->getLastUpdated() );
		}

		function getFromRequest(){
			$this->setListName( (isset($_REQUEST["listName"])) ? $_REQUEST["listName"] : $this->getListName() );
			$this->setDescription( (isset($_REQUEST["description"])) ? $_REQUEST["description"] : $this->getDescription() );
			$this->setOwner( (isset($_REQUEST["owner"])) ? $_REQUEST["owner"] : $this->getOwner() );
			$this->setLastUpdated( (isset($_REQUEST["lastUpdated"])) ? $_REQUEST["lastUpdated"] : $this->getLastUpdated() );
		}

		function save(){
			$id = $this->getId();
			$listName = $this->getListName();
			$description = $this->getDescription();
			$owner = $this->getOwner();
			$lastUpdated = $this->getLastUpdated();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `spotlightlist` SET `listName` = :listName ,`description` = :description ,`owner` = :owner ,`lastUpdated` = :lastUpdated WHERE `id` = :id");
					$query->bindParam('listName', $listName);
					$query->bindParam('description', $description);
					$query->bindParam('owner', $owner);
					$query->bindParam('lastUpdated', $lastUpdated);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `spotlightlist` (`id`,`listName`,`description`,`owner`,`lastUpdated`) VALUES (NULL,:listName,:description,:owner,:lastUpdated);");
					$query->bindParam(':listName', $listName);
					$query->bindParam(':description', $description);
					$query->bindParam(':owner', $owner);
					$query->bindParam(':lastUpdated', $lastUpdated);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `spotlightlist` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByListName($listName){
			if( $this->connection ){
				if( $listName == null && $this->getListName() != ""){
					$listName = $this->getListName();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `listName` = :listName LIMIT 1");
				$query->bindParam(':listName', $listName);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByDescription($description){
			if( $this->connection ){
				if( $description == null && $this->getDescription() != ""){
					$description = $this->getDescription();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `description` = :description LIMIT 1");
				$query->bindParam(':description', $description);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByOwner($owner){
			if( $this->connection ){
				if( $owner == null && $this->getOwner() != ""){
					$owner = $this->getOwner();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `owner` = :owner LIMIT 1");
				$query->bindParam(':owner', $owner);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByLastUpdated($lastUpdated){
			if( $this->connection ){
				if( $lastUpdated == null && $this->getLastUpdated() != ""){
					$lastUpdated = $this->getLastUpdated();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `lastUpdated` = :lastUpdated LIMIT 1");
				$query->bindParam(':lastUpdated', $lastUpdated);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$spotlightlists[] = $result;
					}
					if( is_array( $spotlightlists ) ){
						return $spotlightlists;
					}else{
						return array();
					}

				}
			}
		}

		function getListByListName($listName=null){
			if( $this->connection ){
				if( $listName == null && $this->getListName() != ""){
					$listName = $this->getListName();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `listName` = :listName");
				$query->bindParam(':listName', $listName);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$spotlightlists[] = $result;
					}
					if( is_array( $spotlightlists ) ){
						return $spotlightlists;
					}else{
						return array();
					}

				}
			}
		}

		function getListByDescription($description=null){
			if( $this->connection ){
				if( $description == null && $this->getDescription() != ""){
					$description = $this->getDescription();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `description` = :description");
				$query->bindParam(':description', $description);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$spotlightlists[] = $result;
					}
					if( is_array( $spotlightlists ) ){
						return $spotlightlists;
					}else{
						return array();
					}

				}
			}
		}

		function getListByOwner($owner=null){
			if( $this->connection ){
				if( $owner == null && $this->getOwner() != ""){
					$owner = $this->getOwner();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `owner` = :owner");
				$query->bindParam(':owner', $owner);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$spotlightlists[] = $result;
					}
					if( is_array( $spotlightlists ) ){
						return $spotlightlists;
					}else{
						return array();
					}

				}
			}
		}

		function getListByLastUpdated($lastUpdated=null){
			if( $this->connection ){
				if( $lastUpdated == null && $this->getLastUpdated() != ""){
					$lastUpdated = $this->getLastUpdated();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlist` WHERE `lastUpdated` = :lastUpdated");
				$query->bindParam(':lastUpdated', $lastUpdated);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlist") ){
						$spotlightlists[] = $result;
					}
					if( is_array( $spotlightlists ) ){
						return $spotlightlists;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="spotlightlist.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `spotlightlist` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < sizeof($numParams); $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("spotlightlist") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>