<?php
	/*Class Generated by Brendon Irwin's Class Generator*/

	class Spotlightlistitem{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $listId;
		private $spifId;
		private $itemOrder;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getListId(){
			return $this->listId;
		}

		function setListId($listId){
			$this->listId = $listId;
		}

		function getSpifId(){
			return $this->spifId;
		}

		function setSpifId($spifId){
			$this->spifId = $spifId;
		}

		function getItemOrder(){
			return $this->itemOrder;
		}

		function setItemOrder($itemOrder){
			$this->itemOrder = $itemOrder;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$spotlightlistitem = $query->fetchObject("spotlightlistitem");
					}
					if( is_object( $spotlightlistitem ) ){
						$spotlightlistitem->setConnection( $this->connection );
					}
					return $spotlightlistitem;
				}
			}
		}

		function getFromPost(){
			$this->setListId( (isset($_POST["listId"])) ? $_POST["listId"] : $this->getListId() );
			$this->setSpifId( (isset($_POST["spifId"])) ? $_POST["spifId"] : $this->getSpifId() );
			$this->setItemOrder( (isset($_POST["itemOrder"])) ? $_POST["itemOrder"] : $this->getItemOrder() );
		}

		function getFromRequest(){
			$this->setListId( (isset($_REQUEST["listId"])) ? $_REQUEST["listId"] : $this->getListId() );
			$this->setSpifId( (isset($_REQUEST["spifId"])) ? $_REQUEST["spifId"] : $this->getSpifId() );
			$this->setItemOrder( (isset($_REQUEST["itemOrder"])) ? $_REQUEST["itemOrder"] : $this->getItemOrder() );
		}

		function save(){
			$id = $this->getId();
			$listId = $this->getListId();
			$spifId = $this->getSpifId();
			$itemOrder = $this->getItemOrder();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `spotlightlistitem` SET `listId` = :listId ,`spifId` = :spifId ,`itemOrder` = :itemOrder WHERE `id` = :id");
					$query->bindParam('listId', $listId);
					$query->bindParam('spifId', $spifId);
					$query->bindParam('itemOrder', $itemOrder);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `spotlightlistitem` (`id`,`listId`,`spifId`,`itemOrder`) VALUES (NULL,:listId,:spifId,:itemOrder);");
					$query->bindParam(':listId', $listId);
					$query->bindParam(':spifId', $spifId);
					$query->bindParam(':itemOrder', $itemOrder);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `spotlightlistitem` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByListId($listId){
			if( $this->connection ){
				if( $listId == null && $this->getListId() != ""){
					$listId = $this->getListId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `listId` = :listId LIMIT 1");
				$query->bindParam(':listId', $listId);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getBySpifId($spifId){
			if( $this->connection ){
				if( $spifId == null && $this->getSpifId() != ""){
					$spifId = $this->getSpifId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `spifId` = :spifId LIMIT 1");
				$query->bindParam(':spifId', $spifId);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByItemOrder($itemOrder){
			if( $this->connection ){
				if( $itemOrder == null && $this->getItemOrder() != ""){
					$itemOrder = $this->getItemOrder();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `itemOrder` = :itemOrder LIMIT 1");
				$query->bindParam(':itemOrder', $itemOrder);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$spotlightlistitems[] = $result;
					}
					if( is_array( $spotlightlistitems ) ){
						return $spotlightlistitems;
					}else{
						return array();
					}

				}
			}
		}

		function getListByListId($listId=null){
			if( $this->connection ){
				if( $listId == null && $this->getListId() != ""){
					$listId = $this->getListId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `listId` = :listId");
				$query->bindParam(':listId', $listId);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$spotlightlistitems[] = $result;
					}
					if( is_array( $spotlightlistitems ) ){
						return $spotlightlistitems;
					}else{
						return array();
					}

				}
			}
		}

		function getListBySpifId($spifId=null){
			if( $this->connection ){
				if( $spifId == null && $this->getSpifId() != ""){
					$spifId = $this->getSpifId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `spifId` = :spifId");
				$query->bindParam(':spifId', $spifId);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$spotlightlistitems[] = $result;
					}
					if( is_array( $spotlightlistitems ) ){
						return $spotlightlistitems;
					}else{
						return array();
					}

				}
			}
		}

		function getListByItemOrder($itemOrder=null){
			if( $this->connection ){
				if( $itemOrder == null && $this->getItemOrder() != ""){
					$itemOrder = $this->getItemOrder();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `spotlightlistitem` WHERE `itemOrder` = :itemOrder");
				$query->bindParam(':itemOrder', $itemOrder);

				if( $query->execute() ){
					while( $result = $query->fetchObject("spotlightlistitem") ){
						$spotlightlistitems[] = $result;
					}
					if( is_array( $spotlightlistitems ) ){
						return $spotlightlistitems;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="spotlightlistitem.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `spotlightlistitem` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < sizeof($numParams); $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("spotlightlistitem") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>